version: '3.4'

services:
  app2:
    container_name: app2
    image: app2
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:5002
networks:
  default:
    external:
      name: test_net